### ISSUE TITLE
Arrow keys do not open drop down lists

### ISSUE THREAD

**Issue by jessepearson** [woocommerce/selectWoo#13]
When tabbing into Country or State fields on checkout, the arrow keys do not open dropdown lists. Standard behavior for dropdown lists would be to hit the down arrow to open the list to scroll through it. Presently you have to start typing, or hit Enter/Return. If you do start typing, then the first letter opens the list and is lost, then the rest of the letters get typed into the search.

**Comment by claudiulodro** [comment]
Fixed in https://github.com/woocommerce/woocommerce/pull/17928
