### ISSUE TITLE
Sample pages not working

### ISSUE THREAD

**Issue by deap82** [woocommerce/selectWoo#22]
I'm interested in evaluating this component as we're very much in need of a keyboard friendly and accessible multi select component.

But the sample pages are not working as they reference jquery at 
`https://woocommerce.github.io/selectWoo/vendor/js/jquery.min.js`
which gives 404.

Could this be fixed easily? Are the sample pages part of the source?

**Comment by Leapfrognz** [comment]
Can we get some action on this please. We need usage of this plugin signed off by the clients a11y expert before implementing in a project.

**Comment by cyphix333** [comment]
Just noticed this as well. Anyone awake?
