### ISSUE TITLE
Disable wooSelect on certain field

### ISSUE THREAD

**Issue by seldimi** [woocommerce/selectWoo#32]
Hello all.
How can I disable a custom select field that was added on WooCommerce's checkout page, not to be populated with a live search box?
We have added a selectbox with yes/no option, where search is not need.

I have tried with CSS but the wooSelect html code is appended on body.

**Comment by helgatheviking** [comment]
While this isn't a support forum, I would recommend _not_ enabling it in the first place. Avoid using the CSS classes that trigger SelectWoo and you should get a regular select.

**Comment by seldimi** [comment]
This is not a support question on how to disable it. This is a bug as it auto applies to all select boxes in checkout, including custom fields from woocommerce_form_field

For me wooSelect should be triggered by a class or appended with elements name so we can hide search bar or even disable it to specific select box.

**Comment by helgatheviking** [comment]
Well that's actually a lot clearer. Can you provide some code to reproduce this?

**Comment by seldimi** [comment]
`function webexpert_timologio_for_woocommerce_billing_fields($billing_fields) {
        $billing_fields['billing_invoice'] = array(
            'priority'    => 120,
            'type'        => 'select',
            'label'       => __('I want to issue an invoice', 'webexpert-timologio-for-woocommerce'),
            'placeholder' => _x('Invoice', 'placeholder', 'webexpert-timologio-for-woocommerce'),
            'required'    => false,
            'class'       => array('form-row-wide', 'invoice-select'),
            'clear'       => true,
            'options'     => array(
                'y' => __('Yes', 'webexpert-timologio-for-woocommerce'),
                'n' => __('No', 'webexpert-timologio-for-woocommerce'),
            ),
            'default'     => 'n'
        );
        return $billing_fields;
    }
add_filter('woocommerce_billing_fields', 'webexpert_timologio_for_woocommerce_billing_fields');
`

This will produce the following
https://ibb.co/9ND0HMx

A selectbox of yes/no but also a search bar over it. Search is redundant.

**Comment by helgatheviking** [comment]
Thanks for the code snippet. I can't reproduce with WooCommerce 3.8 and Twenty Nineteen theme.
https://cl.ly/4381d557128e

**Comment by seldimi** [comment]
If you open the select box, don't you see a search bar on top?
Sorry for replying so late.

**Comment by seldimi** [comment]
Hello ?

**Comment by helgatheviking** [comment]
No, I do not see a search bar: https://share.getcloudapp.com/v1urvpW2
Currently using 4.0-beta.

**Comment by seldimi** [comment]
https://tinyurl.com/rmqk3dv
Default Storefront, go to checkout and see it yourself please

**Comment by helgatheviking** [comment]
Cannot reproduce with Storefront either. 

One of your scripts is explicitly initializing `select2` for this field
```
if (jQuery('#billing_invoice').length>0)
            jQuery('#billing_invoice').select2();
```
[src](https://webexpert.design/4seasons/wp-content/plugins/webexpert-timologio-for-woocommerce/public/js/webexpert-timologio-for-woocommerce-public.js?ver=1.0.10)

**Comment by seldimi** [comment]
Woops my bad :( Feels stupid now ..
Sorry for wasting your time

**Comment by seldimi** [comment]
Hey. I was too quick to judge... even if I replace select2 with selectWoo(), the search is still there.

**Comment by seldimi** [comment]
https://select2.org/searching#hiding-the-search-box
That was the solution, so yes selectWoo on storefront brings search box

**Comment by helgatheviking** [comment]
Don't swap it. I was saying don't initialize select2 or selectWoo on that input. Delete that code entirely.

**Comment by seldimi** [comment]
So by default selectWoo initializes search box.
I was doing it for having same appearance as rest select boxes.
Ok thanks
