### ISSUE TITLE
It may soon be time to go back to select2

### ISSUE THREAD

**Issue by scottblinch** [woocommerce/selectWoo#35]
This project was started in response to the fact that select2 development had begun to stagnate, and issues around accessibility were not being properly addressed. However, we are starting to see a lot more activity there, and we're about to see a release containing quite a few accessibility improvements, assuming beta testing goes well (see here: https://github.com/select2/select2/issues/3744#issuecomment-620306247).

Meanwhile, we're unfortunately just not seeing much going on over here anymore. This post isn't meant to bash on the talented developers who spent a lot of their own time doing all this work for free. Sometimes it just is no longer feasible to dedicate to something for one reason or another (I myself don't do any open source work so I certainly cannot be one to talk), and this appears to be one of those times.

This project was great while it was active, and while it's a bummer that it's no longer being worked on, I'm glad to see that select2 is getting love again, as there really aren't many other feasible options for jQuery-based dynamic select boxes out there.

**Comment by claudiosanches** [comment]
Hello @scottblinch, thanks for your comment, I'm aware of the updates from Select2, but Select2 doesn't fix all accessibility issues yet, also note that all releases of SelectWoo are "pre-releases", we only intent to make fixes for WooCommerce for now, so maybe in the future we could go back to Select2, but isn't time yet.

**Comment by kevin-brown** [comment]
> but Select2 doesn't fix all accessibility issues yet

Maintainer of Select2 here. We've been slowly chipping away at accessibility issues over the years (it's a struggle when none of us have proper accessibility training, but we can read specs) and I'm trying to ensure our [ticket list for current accessibility issues](https://github.com/select2/select2/issues?q=is%3Aissue+is%3Aopen+label%3Aaccessibility) is accurate. Is there any chance you can skim over it and let us know what accessibility issues are missing that would prevent SelectWoo from migrating?
