### ISSUE TITLE
aria-label set but doesn't show on screen reader

### ISSUE THREAD

**Issue by kerranm** [woocommerce/selectWoo#8]
Hey folks, we're working on implementing this and while testing with a screen reader we've noticed the aria-label is not showing. It has been explicitly set and appears in the markup but it just doesn't show on the reader. Have you come across this problem before?

**Comment by claudiulodro** [comment]
Yeah, [not all screen readers do anything with the aria-label](https://www.w3.org/WAI/GL/wiki/Using_aria-label_to_provide_an_invisible_label) and some only do things with it in certain contexts.
