### ISSUE TITLE
Multi-select arrow keys don't go through the list

### ISSUE THREAD

**Issue by mikejolley** [woocommerce/selectWoo#9]
If you focus and type something and wait for the list to show, down/up arrows do not let you go through the list and enter does not add the item to the select.

You can see this on the edit order page in WooCommerce, add item.

@claudiulodro

**Comment by claudiulodro** [comment]
Probably something with that specific usage. I'll definitely still investigate but [the multiselect accessibility demo](https://woocommerce.github.io/selectWoo/accessibility-testing/samples/multi.html) works great.

**Comment by claudiulodro** [comment]
Updated here and [in WooCommerce](https://github.com/woocommerce/woocommerce/pull/17380).
